apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyego-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eyego-app
  template:
    metadata:
      labels:
        app: eyego-app
    spec:
      containers:
        - name: eyego-app
          image: "442426864694.dkr.ecr.us-east-1.amazonaws.com/eyego:latest"
          ports: 
            - containerPort: 3000
      imagePullSecrets:
        - name: ecr-secret
                                                                              
