apiVersion: v1
kind: Service
metadata:
  name: eyego-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "3000"
spec:
  selector:
    app: eyego-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000