name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 442426864694
  ECR_URI: 442426864694.dkr.ecr.us-east-1.amazonaws.com/eyego

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: 'v1.24.0'

      - name: Verify kubectl Installation
        run: kubectl version --client

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          for i in {1..5}; do
            echo "Attempt $i: Logging into Amazon ECR..."
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com && break || sleep 5
          done

      - name: Build and Push Docker Image
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          docker build -t eyego:$COMMIT_SHA .
          docker tag eyego:$COMMIT_SHA $ECR_URI:$COMMIT_SHA
          docker tag eyego:$COMMIT_SHA $ECR_URI:latest
          docker push $ECR_URI:$COMMIT_SHA
          docker push $ECR_URI:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name EKS-test
          kubectl config current-context
          kubectl cluster-info

      - name: Verify Cluster Access
        run: |
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          echo "Checking pod status..."
          kubectl get pods -o wide
          kubectl describe deployment eyego-app
